[build]
  publish = "dist"
  command = "npm run build:web"
  base = "project"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[context.production]
  command = "npm ci && npm run build:web"

[context.deploy-preview]
  command = "npm ci && npm run build:web"

[context.branch-deploy]
  command = "npm ci && npm run build:web"

# Form handling for contact forms
[[forms]]
  name = "contact"

# Edge functions
[build.processing]
  skip_processing = false

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://seba-mobile-app.netlify.app"
    sitemapPath = "/sitemap.xml"
