name: Deploy Seba Mobile App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build and test the web version
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: project/package-lock.json
        
    - name: Install dependencies
      run: |
        cd project
        npm ci
        
    - name: Build for web
      run: |
        cd project
        npm run build:web
        
    - name: Run tests
      run: |
        cd project
        npm run test || echo "No tests configured yet"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: project/dist/
        
  # Deploy to GitHub Pages
  deploy-github-pages:
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: project/package-lock.json
        
    - name: Install dependencies
      run: |
        cd project
        npm ci
        
    - name: Build for GitHub Pages
      run: |
        cd project
        npm run build:web
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: project/dist/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
  # Deploy to Netlify
  deploy-netlify:
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: project/package-lock.json
        
    - name: Install dependencies
      run: |
        cd project
        npm ci
        
    - name: Build for web
      run: |
        cd project
        npm run build:web
        
    - name: Deploy to Netlify
      uses: netlify/actions/deploy@master
      with:
        publish-dir: project/dist
        production-branch: main
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
  # Build mobile app with Expo EAS
  build-mobile:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: project/package-lock.json
        
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install dependencies
      run: |
        cd project
        npm ci
        
    - name: Build mobile app
      run: |
        cd project
        npx eas build --platform all --non-interactive
        
  # Create release
  create-release:
    needs: [deploy-github-pages, deploy-netlify, build-mobile]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Seba Mobile App v${{ github.run_number }}
        body: |
          🎉 **Seba Mobile App Release v${{ github.run_number }}**
          
          ## 🚀 Deployed URLs:
          - **GitHub Pages**: https://punam06.github.io/SebaMobileApp/
          - **Netlify**: https://seba-mobile-app.netlify.app/
          - **Expo**: Available in Expo Go
          
          ## 📱 Features:
          - ✅ Bangladeshi Government Services Portal
          - ✅ Real-time search with Bengali support
          - ✅ Mobile-first responsive design
          - ✅ Service application forms
          - ✅ Cross-platform compatibility
          
          ## 🔧 Technical Stack:
          - React Native + Expo
          - TypeScript
          - Tab-based navigation
          - Emoji-based icons for fast loading
          
          ## 📖 Documentation:
          - [Demo Guide](DEMO_GUIDE.md)
          - [Testing Guide](COMPREHENSIVE_TESTING_GUIDE.md)
          - [Deployment Guide](project/DEPLOYMENT.md)
          
          Built with ❤️ for BDApps Innovation Summit
        draft: false
        prerelease: false
